### ISSUE TITLE
File inclusion issue in kinobi template

### ISSUE THREAD

**Issue by Jac0xb** [lorisleiva/kinobi-template#1]
This should be dist/ instead of ./dist or npm publish does include type files. Also there is no "./dist/src/index.d.ts",

https://github.com/lorisleiva/kinobi-template/blob/a8346b9847f7b3e638327f29721ca49a78c1ee50/clients/js/package.json#L16

**Comment by lorisleiva** [comment]
Ah thanks! We've actually moved this template over to [this `create-solana-program` generator](https://github.com/solana-program/create-solana-program) where this bug has been fixed.

I'm gonna mark this repo as archived since `create-solana-program` now replaces this.
